Issue #3062474 by wengerk: Ensure EventTrackerService get the Price using any available Price Resolver
gridonic/commerce_google_tag_manager pull request #39
Opened 2019-06-18 11:32 UTC by WengerK

https://www.drupal.org/project/commerce_google_tag_manager/issues/3062474

2019-06-18 11:33 UTC, WengerK commented on src/EventTrackerService.php
> +    /** @var \Drupal\commerce_price\Price $price */
```suggestion
```

2019-06-18 11:33 UTC, WengerK commented on src/EventTrackerService.php
>      $price = $product_variation->getPrice();
```suggestion
    /** @var \Drupal\commerce_price\Price $price */
    $price = $product_variation->getPrice();
```

2019-06-18 11:33 UTC, WengerK commented on src/EventTrackerService.php
> +      $calculated_price = $this->priceCalculator->calculate($product_variation, 1, $context)->getCalculatedPrice();
```suggestion
	  /** @var \Drupal\commerce_price\Price $calculated_price */
      $calculated_price = $this->priceCalculator->calculate($product_variation, 1, $context)->getCalculatedPrice();
```

2019-06-19 06:43 UTC, WengerK commented on src/EventTrackerService.php
> +      // Ensure the price is available before using it.
```suggestion
```

2019-06-19 06:43 UTC, WengerK commented on tests/src/Kernel/EventTrackerServiceTest.php
> +      'price'  => new Price('11.00', 'USD'),
```suggestion
      'price' => new Price('11.00', 'USD'),
```

2019-06-19 06:44 UTC, WengerK reviewed
Still some mini improvment

2019-06-19 08:12 UTC, wanze requested changes
Thanks for implementing this important update! 👍 🎉Just one minor comment regarding the visibility of the introduced dependencies, then let's merge :)

2019-06-19 08:12 UTC, wanze commented on src/EventTrackerService.php
> +  protected $currentUser;
I think the new dependencies should be `private` to be consistent with the other members.

2019-07-26 07:39 UTC, merged